create extension if not exists pgcrypto;
create extension if not exists pg_cron with schema extensions;

create type public.app_role as enum ('admin', 'staff');
create type public.appointment_status as enum (
  'pending',
  'scheduled',
  'rescheduled',
  'cancelled',
  'completed'
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table public.clinics (
  id bigint generated by default as identity primary key,
  name text not null,
  timezone text not null default 'America/Bogota',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  clinic_id bigint not null references public.clinics(id) on delete restrict,
  email text not null unique,
  full_name text,
  role public.app_role not null default 'admin',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.providers (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  name text not null,
  specialization text not null,
  calendar_id text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.services (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  name text not null,
  duration_min integer not null check (duration_min > 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.patients (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  name text not null,
  phone text not null,
  email text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table public.appointments (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  patient_id bigint not null references public.patients(id) on delete restrict,
  provider_id bigint not null references public.providers(id) on delete restrict,
  service_id bigint not null references public.services(id) on delete restrict,
  start_time timestamptz not null,
  end_time timestamptz not null,
  status public.appointment_status not null default 'pending',
  notes text,
  external_event_id text,
  reminder_sent_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint appointments_time_window check (end_time > start_time)
);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id bigint,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index providers_clinic_name_key on public.providers (clinic_id, name);
create unique index services_clinic_name_key on public.services (clinic_id, name);
create unique index patients_clinic_phone_key on public.patients (clinic_id, phone);

create index appointments_clinic_start_idx on public.appointments (clinic_id, start_time);
create index appointments_status_idx on public.appointments (status);
create index audit_logs_clinic_created_idx on public.audit_logs (clinic_id, created_at desc);

create or replace function public.current_clinic_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select clinic_id
  from public.profiles
  where id = auth.uid()
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  default_clinic_id bigint;
  requested_clinic_id bigint;
  requested_role text;
begin
  select id into default_clinic_id
  from public.clinics
  order by id
  limit 1;

  if default_clinic_id is null then
    insert into public.clinics (name, timezone)
    values ('Nodi Family Clinic', 'America/Bogota')
    returning id into default_clinic_id;
  end if;

  requested_clinic_id := case
    when coalesce(new.raw_user_meta_data ->> 'clinic_id', '') ~ '^[0-9]+$'
      then (new.raw_user_meta_data ->> 'clinic_id')::bigint
    else default_clinic_id
  end;

  requested_role := lower(coalesce(new.raw_user_meta_data ->> 'role', 'admin'));

  insert into public.profiles (id, clinic_id, email, full_name, role)
  values (
    new.id,
    requested_clinic_id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, ''), '@', 1)),
    case when requested_role = 'staff' then 'staff'::public.app_role else 'admin'::public.app_role end
  )
  on conflict (id) do update
  set
    clinic_id = excluded.clinic_id,
    email = excluded.email,
    full_name = excluded.full_name,
    role = excluded.role,
    updated_at = timezone('utc', now());

  return new;
end;
$$;

create or replace function public.log_appointment_changes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_logs (
    clinic_id,
    actor_user_id,
    action,
    entity_type,
    entity_id,
    details
  )
  values (
    coalesce(new.clinic_id, old.clinic_id),
    auth.uid(),
    tg_op,
    'appointment',
    coalesce(new.id, old.id),
    jsonb_build_object(
      'before', to_jsonb(old),
      'after', to_jsonb(new)
    )
  );

  return coalesce(new, old);
end;
$$;

create trigger on_clinics_updated
before update on public.clinics
for each row execute function public.touch_updated_at();

create trigger on_profiles_updated
before update on public.profiles
for each row execute function public.touch_updated_at();

create trigger on_providers_updated
before update on public.providers
for each row execute function public.touch_updated_at();

create trigger on_services_updated
before update on public.services
for each row execute function public.touch_updated_at();

create trigger on_patients_updated
before update on public.patients
for each row execute function public.touch_updated_at();

create trigger on_appointments_updated
before update on public.appointments
for each row execute function public.touch_updated_at();

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create trigger on_appointment_audit
after insert or update or delete on public.appointments
for each row execute function public.log_appointment_changes();

alter table public.clinics enable row level security;
alter table public.profiles enable row level security;
alter table public.providers enable row level security;
alter table public.services enable row level security;
alter table public.patients enable row level security;
alter table public.appointments enable row level security;
alter table public.audit_logs enable row level security;

create policy "clinic staff can read their clinic"
on public.clinics
for select
using (id = public.current_clinic_id());

create policy "clinic admins can update their clinic"
on public.clinics
for update
using (id = public.current_clinic_id())
with check (id = public.current_clinic_id());

create policy "staff can read own profile"
on public.profiles
for select
using (id = auth.uid());

create policy "staff can update own profile"
on public.profiles
for update
using (id = auth.uid())
with check (id = auth.uid());

create policy "staff can select providers in clinic"
on public.providers
for select
using (clinic_id = public.current_clinic_id());

create policy "staff can insert providers in clinic"
on public.providers
for insert
with check (clinic_id = public.current_clinic_id());

create policy "staff can update providers in clinic"
on public.providers
for update
using (clinic_id = public.current_clinic_id())
with check (clinic_id = public.current_clinic_id());

create policy "staff can delete providers in clinic"
on public.providers
for delete
using (clinic_id = public.current_clinic_id());

create policy "staff can select services in clinic"
on public.services
for select
using (clinic_id = public.current_clinic_id());

create policy "staff can insert services in clinic"
on public.services
for insert
with check (clinic_id = public.current_clinic_id());

create policy "staff can update services in clinic"
on public.services
for update
using (clinic_id = public.current_clinic_id())
with check (clinic_id = public.current_clinic_id());

create policy "staff can delete services in clinic"
on public.services
for delete
using (clinic_id = public.current_clinic_id());

create policy "staff can select patients in clinic"
on public.patients
for select
using (clinic_id = public.current_clinic_id());

create policy "staff can insert patients in clinic"
on public.patients
for insert
with check (clinic_id = public.current_clinic_id());

create policy "staff can update patients in clinic"
on public.patients
for update
using (clinic_id = public.current_clinic_id())
with check (clinic_id = public.current_clinic_id());

create policy "staff can delete patients in clinic"
on public.patients
for delete
using (clinic_id = public.current_clinic_id());

create policy "staff can select appointments in clinic"
on public.appointments
for select
using (clinic_id = public.current_clinic_id());

create policy "staff can insert appointments in clinic"
on public.appointments
for insert
with check (clinic_id = public.current_clinic_id());

create policy "staff can update appointments in clinic"
on public.appointments
for update
using (clinic_id = public.current_clinic_id())
with check (clinic_id = public.current_clinic_id());

create policy "staff can delete appointments in clinic"
on public.appointments
for delete
using (clinic_id = public.current_clinic_id());

create policy "staff can read audit logs in clinic"
on public.audit_logs
for select
using (clinic_id = public.current_clinic_id());
