-- ============================================================
-- ESQUEMA COMPLETO - Base de datos Nodi Clinic
-- Generado: 2026-04-07
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- ENUMS
-- ────────────────────────────────────────────────────────────
CREATE TYPE public.app_role AS ENUM ('admin', 'staff');
CREATE TYPE public.appointment_status AS ENUM ('pending', 'scheduled', 'rescheduled', 'cancelled', 'completed');

-- ────────────────────────────────────────────────────────────
-- TABLAS
-- ────────────────────────────────────────────────────────────

-- 1. Clínicas
CREATE TABLE public.clinics (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  brand_name    TEXT,
  slogan        TEXT,
  logo          TEXT,
  description   TEXT,
  timezone      TEXT NOT NULL DEFAULT 'America/Bogota',
  country_code  TEXT NOT NULL DEFAULT 'CO',
  phone_prefix  TEXT NOT NULL DEFAULT '+57',
  city          TEXT,
  address       TEXT,
  work_start_hour INTEGER NOT NULL DEFAULT 8,
  work_end_hour   INTEGER NOT NULL DEFAULT 18,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

-- 2. Perfiles de usuario (extensión de auth.users)
CREATE TABLE public.profiles (
  id          UUID PRIMARY KEY,
  clinic_id   BIGINT NOT NULL REFERENCES public.clinics(id),
  email       TEXT NOT NULL,
  full_name   TEXT,
  first_name  TEXT,
  photo_url   TEXT,
  role        public.app_role NOT NULL DEFAULT 'admin',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

-- 3. Pacientes
CREATE TABLE public.patients (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id     BIGINT NOT NULL REFERENCES public.clinics(id),
  name          TEXT NOT NULL,
  phone         TEXT NOT NULL,
  email         TEXT,
  country_code  TEXT,
  timezone      TEXT NOT NULL DEFAULT 'America/Bogota',
  date_of_birth DATE,
  category      TEXT DEFAULT 'Seguimiento',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

-- 4. Proveedores (médicos / profesionales)
CREATE TABLE public.providers (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id       BIGINT NOT NULL REFERENCES public.clinics(id),
  name            TEXT NOT NULL,
  specialization  TEXT NOT NULL,
  email           TEXT,
  phone           TEXT,
  calendar_id     TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

-- 5. Servicios
CREATE TABLE public.services (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id     BIGINT NOT NULL REFERENCES public.clinics(id),
  name          TEXT NOT NULL,
  description   TEXT,
  specialty     TEXT,
  duration_min  INTEGER NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

-- 6. Relación proveedor ↔ servicio
CREATE TABLE public.provider_services (
  provider_id BIGINT NOT NULL REFERENCES public.providers(id) ON DELETE CASCADE,
  service_id  BIGINT NOT NULL REFERENCES public.services(id) ON DELETE CASCADE,
  PRIMARY KEY (provider_id, service_id)
);

-- 7. Citas
CREATE TABLE public.appointments (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id         BIGINT NOT NULL REFERENCES public.clinics(id),
  patient_id        BIGINT NOT NULL REFERENCES public.patients(id),
  provider_id       BIGINT NOT NULL REFERENCES public.providers(id),
  service_id        BIGINT NOT NULL REFERENCES public.services(id),
  start_time        TIMESTAMPTZ NOT NULL,
  end_time          TIMESTAMPTZ NOT NULL,
  status            public.appointment_status NOT NULL DEFAULT 'pending',
  notes             TEXT,
  external_event_id TEXT,
  reminder_sent_at  TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

-- 8. Logs de auditoría
CREATE TABLE public.audit_logs (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id       BIGINT NOT NULL REFERENCES public.clinics(id),
  actor_user_id   UUID,
  action          TEXT NOT NULL,
  entity_type     TEXT NOT NULL,
  entity_id       BIGINT,
  details         JSONB NOT NULL DEFAULT '{}',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

-- 9. Sesiones de WhatsApp
CREATE TABLE public.whatsapp_sessions (
  phone       TEXT PRIMARY KEY,
  history     JSONB NOT NULL DEFAULT '[]',
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

-- 10. Preferencias de usuario
CREATE TABLE public.user_preferences (
  id                  UUID PRIMARY KEY,
  clinic_id           BIGINT REFERENCES public.clinics(id),
  language            TEXT DEFAULT 'es',
  theme               TEXT DEFAULT 'system',
  notifications_email BOOLEAN DEFAULT true,
  notifications_push  BOOLEAN DEFAULT true,
  created_at          TIMESTAMPTZ DEFAULT timezone('utc', now()),
  updated_at          TIMESTAMPTZ DEFAULT timezone('utc', now())
);

-- ────────────────────────────────────────────────────────────
-- VISTA: Estadísticas diarias
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW public.v_daily_stats AS
SELECT
  c.id   AS clinic_id,
  c.name AS clinic_name,
  (SELECT count(*) FROM patients p WHERE p.clinic_id = c.id) AS total_patients,
  (SELECT count(*) FROM patients p WHERE p.clinic_id = c.id
     AND p.created_at >= date_trunc('month', now())) AS new_patients,
  (SELECT count(*) FROM patients p WHERE p.clinic_id = c.id
     AND p.category = 'Crítico') AS critical_patients,
  (SELECT count(*) FROM appointments a WHERE a.clinic_id = c.id
     AND a.start_time::date = CURRENT_DATE) AS appointments_today,
  (SELECT count(*) FROM appointments a WHERE a.clinic_id = c.id
     AND a.start_time::date = CURRENT_DATE AND a.status = 'pending') AS pending_today,
  (SELECT count(*) FROM appointments a WHERE a.clinic_id = c.id
     AND a.start_time::date = CURRENT_DATE AND a.status = 'completed') AS completed_today,
  (SELECT count(*) FROM appointments a WHERE a.clinic_id = c.id
     AND a.start_time::date = CURRENT_DATE AND a.status = 'cancelled') AS cancelled_today
FROM clinics c;

-- ────────────────────────────────────────────────────────────
-- FUNCIONES
-- ────────────────────────────────────────────────────────────

-- Función auxiliar: actualizar updated_at
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$;

-- Función: obtener clinic_id del usuario actual
CREATE OR REPLACE FUNCTION public.current_clinic_id()
RETURNS BIGINT LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public AS $$
  SELECT clinic_id FROM public.profiles WHERE id = auth.uid()
$$;

-- Función: crear perfil al registrar usuario
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public AS $$
DECLARE
  default_clinic_id BIGINT;
  requested_clinic_id BIGINT;
  requested_role TEXT;
BEGIN
  SELECT id INTO default_clinic_id FROM public.clinics ORDER BY id LIMIT 1;

  IF default_clinic_id IS NULL THEN
    INSERT INTO public.clinics (name, timezone)
    VALUES ('Nodi Family Clinic', 'America/Bogota')
    RETURNING id INTO default_clinic_id;
  END IF;

  requested_clinic_id := CASE
    WHEN coalesce(NEW.raw_user_meta_data ->> 'clinic_id', '') ~ '^[0-9]+$'
      THEN (NEW.raw_user_meta_data ->> 'clinic_id')::BIGINT
    ELSE default_clinic_id
  END;

  requested_role := lower(coalesce(NEW.raw_user_meta_data ->> 'role', 'admin'));

  INSERT INTO public.profiles (id, clinic_id, email, full_name, role)
  VALUES (
    NEW.id,
    requested_clinic_id,
    coalesce(NEW.email, ''),
    coalesce(NEW.raw_user_meta_data ->> 'full_name', split_part(coalesce(NEW.email, ''), '@', 1)),
    CASE WHEN requested_role = 'staff' THEN 'staff'::public.app_role ELSE 'admin'::public.app_role END
  )
  ON CONFLICT (id) DO UPDATE SET
    clinic_id  = EXCLUDED.clinic_id,
    email      = EXCLUDED.email,
    full_name  = EXCLUDED.full_name,
    role       = EXCLUDED.role,
    updated_at = timezone('utc', now());

  RETURN NEW;
END;
$$;

-- Función: auditar cambios en citas
CREATE OR REPLACE FUNCTION public.log_appointment_changes()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public AS $$
BEGIN
  INSERT INTO public.audit_logs (clinic_id, actor_user_id, action, entity_type, entity_id, details)
  VALUES (
    coalesce(NEW.clinic_id, OLD.clinic_id),
    auth.uid(),
    TG_OP,
    'appointment',
    coalesce(NEW.id, OLD.id),
    jsonb_build_object('before', to_jsonb(OLD), 'after', to_jsonb(NEW))
  );
  RETURN coalesce(NEW, OLD);
END;
$$;

-- ────────────────────────────────────────────────────────────
-- TRIGGERS
-- ────────────────────────────────────────────────────────────
CREATE TRIGGER trg_clinics_updated_at    BEFORE UPDATE ON clinics       FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_profiles_updated_at   BEFORE UPDATE ON profiles      FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_patients_updated_at   BEFORE UPDATE ON patients      FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_providers_updated_at  BEFORE UPDATE ON providers     FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_services_updated_at   BEFORE UPDATE ON services      FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_appointments_updated  BEFORE UPDATE ON appointments  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER trg_audit_appointments
  AFTER INSERT OR UPDATE OR DELETE ON appointments
  FOR EACH ROW EXECUTE FUNCTION log_appointment_changes();

-- Trigger en auth.users (ya creado por Supabase, incluido como referencia)
-- CREATE TRIGGER on_auth_user_created
--   AFTER INSERT ON auth.users
--   FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- ────────────────────────────────────────────────────────────
-- RLS (Row Level Security)
-- ────────────────────────────────────────────────────────────
ALTER TABLE clinics            ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles           ENABLE ROW LEVEL SECURITY;
ALTER TABLE patients           ENABLE ROW LEVEL SECURITY;
ALTER TABLE providers          ENABLE ROW LEVEL SECURITY;
ALTER TABLE services           ENABLE ROW LEVEL SECURITY;
ALTER TABLE provider_services  ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments       ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs         ENABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_sessions  ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_preferences   ENABLE ROW LEVEL SECURITY;

-- clinics
CREATE POLICY "clinic staff can read their clinic"    ON clinics FOR SELECT USING (id = current_clinic_id());
CREATE POLICY "clinic admins can update their clinic"  ON clinics FOR UPDATE USING (id = current_clinic_id()) WITH CHECK (id = current_clinic_id());

-- profiles
CREATE POLICY "staff can read own profile"   ON profiles FOR SELECT USING (id = auth.uid());
CREATE POLICY "staff can update own profile" ON profiles FOR UPDATE USING (id = auth.uid()) WITH CHECK (id = auth.uid());

-- patients
CREATE POLICY "staff can select patients in clinic" ON patients FOR SELECT USING (clinic_id = current_clinic_id());
CREATE POLICY "staff can insert patients in clinic" ON patients FOR INSERT WITH CHECK (clinic_id = current_clinic_id());
CREATE POLICY "staff can update patients in clinic" ON patients FOR UPDATE USING (clinic_id = current_clinic_id()) WITH CHECK (clinic_id = current_clinic_id());
CREATE POLICY "staff can delete patients in clinic" ON patients FOR DELETE USING (clinic_id = current_clinic_id());

-- providers
CREATE POLICY "staff can select providers in clinic" ON providers FOR SELECT USING (clinic_id = current_clinic_id());
CREATE POLICY "staff can insert providers in clinic" ON providers FOR INSERT WITH CHECK (clinic_id = current_clinic_id());
CREATE POLICY "staff can update providers in clinic" ON providers FOR UPDATE USING (clinic_id = current_clinic_id()) WITH CHECK (clinic_id = current_clinic_id());
CREATE POLICY "staff can delete providers in clinic" ON providers FOR DELETE USING (clinic_id = current_clinic_id());

-- services
CREATE POLICY "staff can select services in clinic" ON services FOR SELECT USING (clinic_id = current_clinic_id());
CREATE POLICY "staff can insert services in clinic" ON services FOR INSERT WITH CHECK (clinic_id = current_clinic_id());
CREATE POLICY "staff can update services in clinic" ON services FOR UPDATE USING (clinic_id = current_clinic_id()) WITH CHECK (clinic_id = current_clinic_id());
CREATE POLICY "staff can delete services in clinic" ON services FOR DELETE USING (clinic_id = current_clinic_id());

-- provider_services
CREATE POLICY "staff can select provider_services in clinic" ON provider_services FOR SELECT
  USING (EXISTS (SELECT 1 FROM providers p WHERE p.id = provider_services.provider_id AND p.clinic_id = current_clinic_id()));
CREATE POLICY "staff can insert provider_services in clinic" ON provider_services FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM providers p WHERE p.id = provider_services.provider_id AND p.clinic_id = current_clinic_id()));
CREATE POLICY "staff can delete provider_services in clinic" ON provider_services FOR DELETE
  USING (EXISTS (SELECT 1 FROM providers p WHERE p.id = provider_services.provider_id AND p.clinic_id = current_clinic_id()));

-- appointments
CREATE POLICY "staff can select appointments in clinic" ON appointments FOR SELECT USING (clinic_id = current_clinic_id());
CREATE POLICY "staff can insert appointments in clinic" ON appointments FOR INSERT WITH CHECK (clinic_id = current_clinic_id());
CREATE POLICY "staff can update appointments in clinic" ON appointments FOR UPDATE USING (clinic_id = current_clinic_id()) WITH CHECK (clinic_id = current_clinic_id());
CREATE POLICY "staff can delete appointments in clinic" ON appointments FOR DELETE USING (clinic_id = current_clinic_id());

-- audit_logs (solo lectura)
CREATE POLICY "staff can read audit logs in clinic" ON audit_logs FOR SELECT USING (clinic_id = current_clinic_id());

-- whatsapp_sessions
CREATE POLICY "service role full access" ON whatsapp_sessions FOR ALL USING (true) WITH CHECK (true);

-- user_preferences
CREATE POLICY "Users manage own preferences" ON user_preferences FOR ALL USING (id = auth.uid());
